### ISSUE TITLE
Status swapped

### ISSUE THREAD

**Issue by ArdBoone** [soundvibe/ha-danfoss#31]
Hello the Addon worked well for a while, but since a couple of days I've got the issue that heating and cooling are the opposite of the reality. So when the system is cooling the addon shows status heating and the other way around?

No faults or warnings in the log.

Any ideas?

**Comment by ArdBoone** [comment]
Hello,

Any one else has this problem?

With MQTT Explorer I can sea that the MQTT message is stating that the system is in mode=heating but the reality and the Danfoss app states its cooling.

{
  "state": "22.0",
  "attributes": {
    "unit_of_measurement": "°C",
    "temperature_low": "5.0",
    "friendly_name": "Woonkamer - Hal - Bijkeuken temperature",
    "temperature_away": "15.0",
    "state_class": "measurement",
    "mode": "heat",
    "device_class": "temperature",
    "temperature_target": "20.0",
    "availability": "online",
    "temperature_high": "35.0",
    "battery_level": "100",
    "temperature_sleep": "17.0",
    "preset": "home",
    "room_number": "0",
    "temperature_home": "20.0"
  }
}

**Comment by soundvibe** [comment]
Hey, could you look into [this](https://github.com/soundvibe/ha-danfoss/issues/15) issue? It had similar issue but it was fixed.

**Comment by Wartopia** [comment]
> Hey, could you look into [this](https://github.com/soundvibe/ha-danfoss/issues/15) issue? It had similar issue but it was fixed.

I have the same issue, i had 3.8 local and since a few month al it does is "heat" never "cool" but it worked before.

Now i removed the local 3.8 and did 4.5 add-on by store rep for future updates and still the same issue. payload is always "heat" while it should be "cool"

Something changed in HA and not the add-on. 

I get some errors aswell, maybe thats why.

`15:49:58.016 [SDG socket thread.1] INFO  i.g.s.opensdg.java.Connection - Async I/O error: java.io.EOFException: Connection closed by grid
15:49:58.024 [pool-1-thread-1] INFO  n.s.h.d.protocol.SDGPeerConnector - Connecting to peer `

**Comment by brambo123** [comment]
I'm running into the same issue.
Just installed the add-on.
The heat pump is cooling the house, but heatingState=HEAT is incorrect.
``
[SDG socket thread.1] DEBUG n.s.h.d.protocol.IconRoomHandler - room=Room{roomName='Hal', temperature=22.43, temperatureFloor=-327.68, temperatureFloorMin=18.0, temperatureFloorMax=35.0, setPointHigh=35.0, setPointLow=4.0, setPointHome=14.0, setPointAway=15.0, setPointSleep=17.0, batteryPercent=100, roomMode=HOME, manualControl=true, heatingState=HEAT, roomNumber=16}
``

A possible cause could be the installation mode.
My installation is set to mode 4; the heat pump is sending a signal that cooling mode is active.
Therefore, the thermostats do not determine whether heating or cooling is active.

**Comment by brambo123** [comment]
Quick debugging yielded the following info:

https://github.com/soundvibe/ha-danfoss/blob/c0293c406629e2e8331697abdc105882978b3fcf/danfoss-addon/src/main/java/net/soundvibe/hasio/danfoss/protocol/IconMasterHandler.java#L147-L150
RAIL_INPUTHEATORCOOL is received separately for each rail (RAIL_FIRST to RAIL_LAST).
However, our installation is set to cooling, but only the first rail has value 0x01; the other 2 are 0x00.
I think this code should therefore be limited to the first (master) rail.



https://github.com/soundvibe/ha-danfoss/blob/c0293c406629e2e8331697abdc105882978b3fcf/danfoss-addon/src/main/java/net/soundvibe/hasio/danfoss/protocol/IconRoomHandler.java#L143-L148
ROOM_HEATINGCOOLINGSTATE is read as a boolean.
In cooling mode, value 0 seems to mean off and 2 means cooling.
Isn't it simply 0=OFF, 1=HEAT, 2=COOL?

**Comment by Wartopia** [comment]
> Quick debugging yielded the following info:
> 
> [ha-danfoss/danfoss-addon/src/main/java/net/soundvibe/hasio/danfoss/protocol/IconMasterHandler.java](https://github.com/soundvibe/ha-danfoss/blob/c0293c406629e2e8331697abdc105882978b3fcf/danfoss-addon/src/main/java/net/soundvibe/hasio/danfoss/protocol/IconMasterHandler.java#L147-L150)
> 
> Lines 147 to 150 in [c0293c4](/soundvibe/ha-danfoss/commit/c0293c406629e2e8331697abdc105882978b3fcf)
> 
>  case RAIL_INPUTHEATORCOOL: 
>      var coolingEnabled = pkt.getBoolean(); 
>      this.roomsByName.forEach((_, iconRoomHandler) -> iconRoomHandler.setHeatingState(coolingEnabled)); 
>      break; 
> 
> RAIL_INPUTHEATORCOOL is received separately for each rail (RAIL_FIRST to RAIL_LAST).
> However, our installation is set to cooling, but only the first rail has value 0x01; the other 2 are 0x00.
> I think this code should therefore be limited to the first (master) rail.
> [ha-danfoss/danfoss-addon/src/main/java/net/soundvibe/hasio/danfoss/protocol/IconRoomHandler.java](https://github.com/soundvibe/ha-danfoss/blob/c0293c406629e2e8331697abdc105882978b3fcf/danfoss-addon/src/main/java/net/soundvibe/hasio/danfoss/protocol/IconRoomHandler.java#L143-L148)
> 
> Lines 143 to 148 in [c0293c4](/soundvibe/ha-danfoss/commit/c0293c406629e2e8331697abdc105882978b3fcf)
> 
>  case ROOM_HEATINGCOOLINGSTATE: 
>      lock.writeLock().lock(); 
>      room.heatingCoolingOn = pkt.getBoolean(); 
>      room.heatingState = HeatingState.from(room.heatingCoolingOn, room.coolingEnabled); 
>      lock.writeLock().unlock(); 
>      break; 
> 
> ROOM_HEATINGCOOLINGSTATE is read as a boolean.
> In cooling mode, value 0 seems to mean off and 2 means cooling.
> Isn't it simply 0=OFF, 1=HEAT, 2=COOL?

Can we test this ourselves somehow?

Because the OG dev is not very active :(

**Comment by brambo123** [comment]
> 
> Can we test this ourselves somehow?
> 
> Because the OG dev is not very active :(

I made a clone to test: https://github.com/brambo123/ha-danfoss
I am not a Java expert, so don't expect too much from me.
I run Docker myself; not as add-in.
By setting "logLevel": "debug" in /data/options.json, you now get information about every packet.
And I have now set RAIL_INPUTHEATORCOOL for only the first rail.

**Comment by soundvibe** [comment]
Feel free to open PR with your changes if you managed to debug this properly and found the issue. I don't have such setup at my house so it's impossible for me to test this.
For backwards compatibility, new config could be added for this and all these changes you made could work when this config is enabled. This way we won't break existing code and I can merge the changes and release new version safely.

**Comment by soundvibe** [comment]
Also, @brambo123 , were you able to validate that `ROOM_HEATINGCOOLINGSTATE` is `0=OFF, 1=HEAT, 2=COOL`? If so, I could update the code and it would make the whole logic much simpler.

P.S. I released a new version using these values. Would be nice if you upgraded and checked if this fixes your issue.

**Comment by brambo123** [comment]
I don't have an icon setup in my own home either, only a remote installation, which is therefore a bit harder to test with.
As soon as the outside temperature has dropped a bit, the cooling is switched off, and I can check if indeed 1=HEAT.

It would be nice if there was a debug log of all packets.
I added this line right now: https://github.com/soundvibe/ha-danfoss/commit/15076f52db905df194cca53734c2980a5276156f
I don't know if IconMasterHandler.java‎ is really the right place, maybe SDGPeerConnector.java or DeviSmartConnection.java is a better place?

One thing I am pretty sure of:
ROOM_COOLINGENABLED is a configuration bit on the thermostat that cooling is allowed.
I have 1 room where cooling is disabled, the shower room, and that is the only one where it is 0 while the rest are all 1.

**Comment by Wartopia** [comment]
> Also, [@brambo123](https://github.com/brambo123) , were you able to validate that `ROOM_HEATINGCOOLINGSTATE` is `0=OFF, 1=HEAT, 2=COOL`? If so, I could update the code and it would make the whole logic much simpler.
> 
> P.S. I released a new version using these values. Would be nice if you upgraded and checked if this fixes your issue.

I did update en it worked. I see cooling now. I cannot test heat since it really hot.

<img width="1080" height="2410" alt="Image" src="https://github.com/user-attachments/assets/45f62802-d6e8-4242-bb1d-bbc1edb4e28e" />

**Comment by soundvibe** [comment]
> > Also, [@brambo123](https://github.com/brambo123) , were you able to validate that `ROOM_HEATINGCOOLINGSTATE` is `0=OFF, 1=HEAT, 2=COOL`? If so, I could update the code and it would make the whole logic much simpler.
> > P.S. I released a new version using these values. Would be nice if you upgraded and checked if this fixes your issue.
> 
> I did update en it worked. I see cooling now. I cannot test heat since it really hot.
> 
> <img alt="Image" width="896" height="2000" src="https://private-user-images.githubusercontent.com/20534055/611269030-45f62802-d6e8-4242-bb1d-bbc1edb4e28e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODIxNDE1MTIsIm5iZiI6MTc4MjE0MTIxMiwicGF0aCI6Ii8yMDUzNDA1NS82MTEyNjkwMzAtNDVmNjI4MDItZDZlOC00MjQyLWJiMWQtYmJjMWVkYjRlMjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNjIyVDE1MTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNTJkOTE4NDViYzliOTkwYjM3ODU2ODk0Nzk5YzdjODI3MTU3NTU3N2Q5NDc2NmZmNzdkZWM5MTgyZDRlZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.9TAfGnGxzdq60UtkNV9sxhEdjmjhK1BmoHs-K1iAhww">

Heat works for me, so I guess this issue should be fixed now 🎉

**Comment by Wartopia** [comment]
> > > Also, [@brambo123](https://github.com/brambo123) , were you able to validate that `ROOM_HEATINGCOOLINGSTATE` is `0=OFF, 1=HEAT, 2=COOL`? If so, I could update the code and it would make the whole logic much simpler.
> > > P.S. I released a new version using these values. Would be nice if you upgraded and checked if this fixes your issue.
> > 
> > 
> > I did update en it worked. I see cooling now. I cannot test heat since it really hot.
> > <img alt="Image" width="896" height="2000" src="https://private-user-images.githubusercontent.com/20534055/611269030-45f62802-d6e8-4242-bb1d-bbc1edb4e28e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODIxNDE1MTIsIm5iZiI6MTc4MjE0MTIxMiwicGF0aCI6Ii8yMDUzNDA1NS82MTEyNjkwMzAtNDVmNjI4MDItZDZlOC00MjQyLWJiMWQtYmJjMWVkYjRlMjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNjIyVDE1MTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNTJkOTE4NDViYzliOTkwYjM3ODU2ODk0Nzk5YzdjODI3MTU3NTU3N2Q5NDc2NmZmNzdkZWM5MTgyZDRlZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.9TAfGnGxzdq60UtkNV9sxhEdjmjhK1BmoHs-K1iAhww">
> 
> Heat works for me, so I guess this issue should be fixed now 🎉

Yes, guess so. But you broke HACS, the app is gone and its working as a shadow app in HA now....

Cant update it anymore or install. Its gone with the wind :s 

Edit:
Sorry, my fault. I see this is not a HACS app but a special one in the normal app store, where i never go....

There its running 0.4.8 


<img width="1080" height="2410" alt="Image" src="https://github.com/user-attachments/assets/e133a16d-db77-419a-ae4c-9ecc27d18fad" />

**Comment by soundvibe** [comment]
fixed in #36
